kind: ServiceAccount
apiVersion: v1
metadata:
  name: daskkubernetes
  namespace: default

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: daskkubernetes
  namespace: default
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "delete"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: daskkubernetes-jsp
  namespace: default
subjects:
- kind: ServiceAccount
  name: jsp-work@jsp-work.iam.gserviceaccount.com
roleRef:
  kind: Role
  name: daskkubernetes
  apiGroup: rbac.authorization.k8s.io
